version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tc-store-net-tools_web_1
      APP_PORT: 3500

  web:
    image: ghcr.io/thomaskn/net-tools:1.1.0
    container_name: tc-store-net-tools_web_1
    restart: on-failure
    environment:
      RPC_HOST: 10.21.21.7
      RPC_PORT: 9332
      PORT: 3500
    volumes:
      - ${APP_DATA_DIR}/data:/data
